name: nu-pan
channels:
- https://conda.anaconda.org/conda-forge
dependencies:
- astropy=5.1
- cartopy
- cftime=1.5.1.1
- cmasher
- ipykernel=6.4.1
- matplotlib=3.5.0
- metpy=1.3.1
- netcdf4=1.5.7
- numpy=1.21.2
- pandas=1.3.4
- pydap=3.3.0
- pyhdf=0.10
- requests=2.27.1
- scikit-learn=1.2.0
- scipy=1.7.1
- seaborn=0.11.2
- setuptools=58.0.4
- shap
- shapely=1.8.4
- tqdm
- webob=1.8.7
- xarray=0.19.0
- yaml=0.2.5

