name: nu-pan
channels:
- https://conda.anaconda.org/conda-forge
dependencies:
- _libgcc_mutex=0.1
- _openmp_mutex=4.5
- alsa-lib=1.2.8
- astropy=5.1.1
- attr=2.5.1
- backcall=0.2.0
- beautifulsoup4=4.12.3
- brotli=1.1.0
- brotli-bin=1.1.0
- brotli-python=1.1.0
- bzip2=1.0.8
- c-ares=1.34.4
- ca-certificates=2024.12.14
- cairo=1.16.0
- cartopy=0.23.0
- certifi=2024.8.30
- cftime=1.5.1.1
- charset-normalizer=2.0.12
- cloudpickle=3.1.1
- cmasher=1.8.0
- colorama=0.4.6
- colorspacious=1.1.2
- curl=8.1.2
- cycler=0.12.1
- dbus=1.13.6
- debugpy=1.8.11
- decorator=5.1.1
- docopt=0.6.2
- entrypoints=0.4
- expat=2.6.4
- fftw=3.3.10
- font-ttf-dejavu-sans-mono=2.37
- font-ttf-inconsolata=3.000
- font-ttf-source-code-pro=2.038
- font-ttf-ubuntu=0.83
- fontconfig=2.14.2
- fonts-conda-ecosystem=1
- fonts-conda-forge=1
- fonttools=4.55.3
- freetype=2.12.1
- geos=3.11.0
- gettext=0.22.5
- gettext-tools=0.22.5
- glib=2.80.2
- glib-tools=2.80.2
- graphite2=1.3.13
- gst-plugins-base=1.22.0
- gstreamer=1.22.0
- gstreamer-orc=0.4.40
- harfbuzz=6.0.0
- hdf4=4.2.15
- hdf5=1.12.1
- icu=70.1
- idna=3.10
- importlib-metadata=8.5.0
- importlib_resources=6.4.5
- ipykernel=6.4.1
- ipython=7.33.0
- ipython_genutils=0.2.0
- jack=1.9.22
- jedi=0.19.2
- jinja2=3.1.4
- joblib=1.4.2
- jpeg=9e
- jupyter_client=7.4.9
- jupyter_core=5.7.2
- keyutils=1.6.1
- kiwisolver=1.4.7
- krb5=1.20.1
- lame=3.100
- lcms2=2.15
- ld_impl_linux-64=2.43
- lerc=4.0.0
- libasprintf=0.22.5
- libasprintf-devel=0.22.5
- libblas=3.9.0
- libbrotlicommon=1.1.0
- libbrotlidec=1.1.0
- libbrotlienc=1.1.0
- libcap=2.67
- libcblas=3.9.0
- libclang=15.0.7
- libclang13=15.0.7
- libcups=2.3.3
- libcurl=8.1.2
- libdb=6.2.32
- libdeflate=1.17
- libedit=3.1.20191231
- libev=4.33
- libevent=2.1.10
- libexpat=2.6.4
- libffi=3.4.2
- libflac=1.4.3
- libgcc=14.2.0
- libgcc-ng=14.2.0
- libgcrypt=1.11.0
- libgcrypt-devel=1.11.0
- libgcrypt-lib=1.11.0
- libgcrypt-tools=1.11.0
- libgettextpo=0.22.5
- libgettextpo-devel=0.22.5
- libgfortran=14.2.0
- libgfortran-ng=14.2.0
- libgfortran5=14.2.0
- libglib=2.80.2
- libgomp=14.2.0
- libgpg-error=1.51
- libiconv=1.17
- liblapack=3.9.0
- libllvm11=11.1.0
- libllvm15=15.0.7
- liblzma=5.6.3
- liblzma-devel=5.6.3
- libnetcdf=4.8.1
- libnghttp2=1.58.0
- libnsl=2.0.1
- libogg=1.3.5
- libopenblas=0.3.25
- libopus=1.3.1
- libpng=1.6.43
- libpq=15.3
- libsndfile=1.2.2
- libsodium=1.0.18
- libsqlite=3.46.0
- libssh2=1.11.0
- libstdcxx=14.2.0
- libstdcxx-ng=14.2.0
- libsystemd0=253
- libtiff=4.5.0
- libtool=2.4.7
- libudev1=253
- libuuid=2.38.1
- libvorbis=1.3.7
- libwebp-base=1.4.0
- libxcb=1.13
- libxkbcommon=1.5.0
- libxml2=2.10.3
- libzip=1.10.1
- libzlib=1.2.13
- llvmlite=0.39.1
- lz4-c=1.9.4
- markupsafe=3.0.2
- matplotlib=3.5.0
- matplotlib-base=3.5.0
- matplotlib-inline=0.1.7
- metpy=1.3.1
- mpg123=1.32.9
- munkres=1.1.4
- mysql-common=8.0.33
- mysql-libs=8.0.33
- ncurses=6.5
- nest-asyncio=1.6.0
- netcdf4=1.5.7
- nspr=4.36
- nss=3.100
- numba=0.56.4
- numpy=1.21.2
- openjpeg=2.5.0
- openssl=3.1.7
- packaging=24.2
- pandas=1.3.4
- parso=0.8.4
- patsy=1.0.1
- pcre2=10.43
- pexpect=4.9.0
- pickleshare=0.7.5
- pillow=9.4.0
- pint=0.23
- pip=24.3.1
- pixman=0.44.2
- platformdirs=4.3.6
- ply=3.11
- pooch=1.8.2
- proj=9.2.1
- prompt-toolkit=3.0.48
- pthread-stubs=0.4
- ptyprocess=0.7.0
- pulseaudio=16.1
- pulseaudio-client=16.1
- pulseaudio-daemon=16.1
- pydap=3.3.0
- pyerfa=2.0.1.5
- pygments=2.18.0
- pyhdf=0.10.2
- pyparsing=3.2.0
- pyproj=3.6.1
- pyqt=5.15.9
- pyqt5-sip=12.12.2
- pyshp=2.3.1
- pysocks=1.7.1
- python=3.9.18
- python-dateutil=2.9.0.post0
- python_abi=3.9
- pytz=2024.2
- pyyaml=6.0.2
- pyzmq=26.2.0
- qt-main=5.15.8
- readline=8.2
- requests=2.27.1
- scikit-learn=1.2.0
- scipy=1.7.1
- seaborn=0.11.2
- seaborn-base=0.11.2
- setuptools=58.0.4
- shap=0.46.0
- shapely=1.8.4
- sip=6.7.12
- six=1.17.0
- slicer=0.0.8
- soupsieve=2.5
- sqlite=3.46.0
- statsmodels=0.13.5
- threadpoolctl=3.5.0
- tk=8.6.13
- toml=0.10.2
- tomli=2.2.1
- tornado=6.4.2
- tqdm=4.67.1
- traitlets=5.14.3
- typing_extensions=4.12.2
- tzdata=2024b
- unicodedata2=15.1.0
- urllib3=1.26.19
- wcwidth=0.2.13
- webob=1.8.7
- wheel=0.45.1
- xarray=0.19.0
- xcb-util=0.4.0
- xcb-util-image=0.4.0
- xcb-util-keysyms=0.4.0
- xcb-util-renderutil=0.3.9
- xcb-util-wm=0.4.1
- xkeyboard-config=2.38
- xorg-kbproto=1.0.7
- xorg-libice=1.1.2
- xorg-libsm=1.2.5
- xorg-libx11=1.8.4
- xorg-libxau=1.0.12
- xorg-libxdmcp=1.1.5
- xorg-libxext=1.3.4
- xorg-libxrender=0.9.10
- xorg-renderproto=0.11.1
- xorg-xextproto=7.3.0
- xorg-xproto=7.0.31
- xz=5.6.3
- xz-gpl-tools=5.6.3
- xz-tools=5.6.3
- yaml=0.2.5
- zeromq=4.3.5
- zipp=3.21.0
- zlib=1.2.13
- zstd=1.5.6

